# Generated by Django 5.0.3 on 2024-05-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_qty',
            new_name='product_quantity',
        ),
    ]
