# Generated by Django 5.0.3 on 2024-05-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_order_orderitem_order_products_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
