# Generated by Django 5.0.3 on 2024-05-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='code',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_used',
            field=models.CharField(null=True),
        ),
    ]
