# Generated by Django 5.0.3 on 2024-05-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_cart_code_order_coupon_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
