# Generated by Django 5.0.3 on 2024-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_discount_amount',
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
