# Generated by Django 5.0.3 on 2024-05-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_remove_cart_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
