# Generated by Django 5.0.3 on 2024-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_alter_order_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash on delivery', 'Cash on delivery'), ('walletbalance', 'Wallet Balance'), ('razorpay', 'Pay with Pay with Razorpay')], max_length=100, null=True),
        ),
    ]
