# Generated by Django 5.0.3 on 2024-04-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='dimensions',
            new_name='size',
        ),
    ]
