# Generated by Django 5.0.3 on 2024-04-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_dimensions_products_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sku',
        ),
    ]
